apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - deployment.yaml
images:
  - name: ghcr.io/unkhz/pjazz:latest
    newTag: 362b599e200bfefbf42053eb701c3212b66995d9
