name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    if: ${{ ! endsWith(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup node 20
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Run npm install
        run: npm install

      - name: Run dist build
        run: |
          echo "Run npm build..."
          npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:latest, ghcr.io/${{ github.repository }}:${{ github.sha }}

      - uses: mikefarah/yq@master
        with:
          cmd: yq --version

      - name: Update image version tag
        run: |
          git config --global user.email "juhani.pelli@gmail.com"
          git config --global user.name "Juhani Pelli"
          yq e '.images[0].newTag = "${{ github.sha }}"' -i .khz-k3s/kustomization.yaml
          git add .khz-k3s/kustomization.yaml
          git commit -m "Deploy ${{ github.sha }} [skip ci]"
          git push origin ${{ github.event.repository.default_branch }}
